# configs/envs/push.yaml

id: PandaPush-v3

# Whether to use dense shaping
dense_reward: false

# Arguments passed to gym.make(env_id, **kwargs)
kwargs:
  render_mode: null  # Use 'human' if you want live rendering

# Table properties
table:
  half_size: [0.5, 0.5]
  obj_z_threshold: -0.01

# Obstacle settings
obstacle:
  n: 0
  radius_range: [0.03, 0.07]
  height_range: [0.05, 0.1]

# Initial spacing constraints
min_obj_goal_dist: 0.05

# Reward shaping coefficients
reward:
  w_ee_obj: 1.0
  w_obj_goal: 1.0
  success_bonus: 5.0
  obstacle_penalty: 2.0
