name: SAC_ID_AUX  # custom class from sac_id_aux.py
policy: MlpPolicy

learning_rate: 3e-4
buffer_size: 1_000_000
learning_starts: 5_000
batch_size: 256
tau: 0.005
gamma: 0.99
train_freq: 1
gradient_steps: 5
ent_coef: auto
use_sde: false

net_arch: [256, 256]

her: true
normalize_actions: true

auxiliary:
  enabled: true
  type: inverse_dynamics
  loss_weight: 0.1
  hidden_units: [256, 256]
