# configs/agent/sac_her.yaml

name: SAC
policy: MultiInputPolicy

learning_rate: 3e-4
buffer_size: 1_000_000
learning_starts: 1_600
batch_size: 256
gamma: 0.95
tau: 0.005
train_freq: 1
gradient_steps: 10
ent_coef: auto
use_sde: false

net_arch: [256, 256]

# HER integration
her: true

auxiliary:
  enabled: false
